### ISSUE TITLE
Can't work with NavBarIcon

### ISSUE THREAD

**Issue by rautram** [cesardeazevedo/react-native-collapsing-toolbar#16]

**Comment by cesardeazevedo** [comment]
Hi, can you provide a description on what's going on? so i can help you.

Thanks

**Comment by rautram** [comment]
Thanks for this awesome library. My issue was solved by using the props of ToolbarAndroid, the issue was i couldn't find a way to deal with the navBarIcon. Can you suggest me the ios alternative of this library. Thanks for the quick response.

**Comment by cesardeazevedo** [comment]
The navBarIcon you mean the `navIconName` from the <Icon.ToolbarAndroid /> in the example?

```jsx
<Icon.ToolbarAndroid
  iconColor='white'
  actions={[{ title: 'Show' }, { title: 'Hide' }]}
  navIconName={'md-menu'}
 />
```

If yes, they come from the [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons), which you have to install separately, and manually link the font icon files.

About the iOS solution, i only have seen react-native js based solutions, since there's no native component from apple that we can based on, you can just use you creativity and do something similar  with Animated.View, there's a good article from App & Flow showing how you could implement it.
https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e

I recommend you creating a `CollapsingHeader.android.js` using this native component on android, and create a `CollapsingHeader.ios.js` and take the approach from the article.

**Comment by rautram** [comment]
Thanks the issue is now resolved.
