### ISSUE TITLE
Works on iOS?

### ISSUE THREAD

**Issue by fauzzi** [cesardeazevedo/react-native-collapsing-toolbar#5]
is this support for iOS?

thanks for advance

**Comment by cesardeazevedo** [comment]
No, it's completely native component, and i was carefully design to just wrap the [CollapsingToolbarLayout](https://developer.android.com/reference/android/support/design/widget/CollapsingToolbarLayout.html), so that's why the name.

There's a bunch cross plataform components out there's. but all of them doesn't look like a native fell.

I know that's not very convenient, but is the only way if you want to do good apps that look native on android, i recommend you to create a `Toolbar.android.js` and use this library, and then create a `Toolbar.ios.js` and take a different approach.
